config/routes.rb
Rails.application.routes.draw do

  get 'scheduled_shifts/create'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users do
    resources :requests
  end

  resources :posts do
    resources :comments
  end

  resources :tags

  resources :shifts
  
  post 'users/:id/edit' => 'users#edit'
  post 'requests/new' => 'requests#create'

  root 'users#index'
  

end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  has_many :shifts

  accepts_nested_attributes_for :shifts
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  respond_to :html, :js, :json

  def new
    @user = User.find(current_user.id)
    @request = Request.find_or_create_by(user_id: @user.id)
    @shifts = Shift.all
  end

  def create
    @request = Request.new(request_params)
    @request.save
    redirect_to user_request_path(current_user.id, @request)
  end

  def show
    @user = current_user
    @request = Request.find_by_id(params[:id])
    respond_with @request
  end

  def edit
    @user = User.find(current_user.id)
    @request = Request.find_by(user_id: @user.id)
  end

  def update
    @request = Request.find(params[:id])
    if @request.update_attributes(request_params)
      redirect_to user_request_path(current_user.id, @request)
    else
      render 'edit'
    end
  end

  private
  def request_params
    params.require(:request).permit(:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :user_id)
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_availability.html.erb
<br><strong>Availability</strong> 
<% if !user.request %>
  <%= link_to "(new)", new_user_request_path(user.id) %>
<% else %>
  <%= link_to "(edit)", edit_user_request_path(user, user.request) unless user.email != current_user.email %>
<% end %>

<% if !user.request %>
 <br><em>Not submitted</em><br>
<% elsif days.map {|day| user.request.send(day.downcase)}.uniq[0].blank? %>
  <br><em>No availability</em><br>
<% elsif user.request %>
  <% days.each do |day| %>
    <% if user.request.send(day.downcase) != "" %>
      <br><%= "#{day}: #{user.request.send(day.downcase)}" %>
    <% end %>
  <% end %><br>
<% end %>

app/views/requests/_form.html.erb
<% if current_user.email == @user.email %>
    
    <h2>Request Form</h2>
    <strong>Availability</strong>

    <%= form_for [@user, @request] do |f| %>

        <br><%= label :monday, "Monday:" %>
        <%= f.text_field :monday %><br>

        <br><%= label :tuesday, "Tuesday:" %>
        <%= f.text_field :tuesday %><br>

        <br><%= label :wednesday, "Wednesday:" %>
        <%= f.text_field :wednesday %><br>

        <br><%= label :thursday, "Thursday:" %>
        <%= f.text_field :thursday %><br>

        <br><%= label :friday, "Friday:" %>
        <%= f.text_field :friday %><br>

        <br><%= label :saturday, "Saturday:" %>
        <%= f.text_field :saturday %><br>

        <br><%= label :sunday, "Sunday:" %>
        <%= f.text_field :sunday %><br>

        <%= f.hidden_field :user_id, value: current_user.id %>

        <br><%= f.submit %>
        
    <% end %><br>

<% end %>

app/views/requests/edit.html.erb
<%= render partial: "form", locals: {user: @user, request: @request} %><br>

app/views/requests/new.html.erb
<%= render partial: "form", locals: {user: @user, request: @request} %><br>

app/views/requests/show.html.erb
<h2><%= @user.name.split(" ")[0] %>'s Request</h2>
<em>Last updated on <%= @request.updated_at.strftime("%A, %b #{Time.now.strftime("%e")}") %></em><br>

<%= render partial: "availability", locals: {user: @user, request: @request} %><br>