config/routes.rb
Rails.application.routes.draw do

  get 'scheduled_shifts/create'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users do
    resources :requests
  end

  resources :posts do
    resources :comments
  end

  resources :tags

  resources :shifts
  
  post 'users/:id/edit' => 'users#edit'
  post 'requests/new' => 'requests#create'

  root 'users#index'
  

end

app/models/shift.rb
class Shift < ActiveRecord::Base
  has_many :scheduled_shifts
  has_many :users, through: :scheduled_shifts

  def add_shift(shift_id)
    scheduled_shift = scheduled_shift.find_by(shift_id: shift_id) 
    if !scheduled_shift
      scheduled_shift = self.scheduled_shifts.build(shift_id: shift_id)
    end
    scheduled_shift
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :find_shift, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js, :json

  def index
    @shifts = Shift.all
    respond_with @shifts
  end

  def new
    @shift = Shift.new
    respond_with @shift
  end

  def create
    @shift = Shift.create(shift_params)
    respond_with @shift
  end

  def show
    respond_with @shift
  end

  def edit
  end

  def update
    if @shift.update_attributes(shift_params)
      redirect_to @shift
    else
      render 'edit'
    end
  end

  def destroy
    @shift.destroy
    redirect_to shifts_path
  end

  private

  def shift_params
    params.require(:shift).permit(:role, :staff, :time, :day)
  end

  def find_shift
    @shift = Shift.find(params[:id])
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= form_for @shift, remote: true do |f| %>

  <div>
    <%= f.label :day, "Day:" %>
    <%= f.select :day, days, prompt: '', required: true %><br><br>
  </div>

  <div>
    <%= f.label :role, "Type:" %>
    <%= f.select :role, [ 'Manager','Counter','Busser' ], prompt: '', required: true %><br><br>
  </div>

  <div>
    <%= f.label :time, "Time:" %>
    <%= f.text_field :time, required: true %><br><br>
  </div>

  <div>
    <%= f.label :staff, "Staff needed:" %>
    <%= f.number_field :staff, style: 'width: 35px', in: 1..5, required: true %><br><br>
  </div>

  <%= f.submit %>
<% end %>

app/views/shifts/create.js.erb
$('#new_shift').detach();
$('#new_link').show();

app/views/shifts/edit.html.erb
<% if admin %>

  <h1>Shifts#edit</h1>
  <p>Find me in app/views/shifts/edit.html.erb</p>

  <%= render partial: "form", locals: {shift: @shift} %>

<% end %>

app/views/shifts/index.html.erb
<% if admin %>

  <h1>Shifts#index</h1>
  <p>Find me in app/views/shifts/index.html.erb</p>

  <%= link_to "Add Shift", new_shift_path, id: "new_link", remote: true %><br>

  <table>
  <!-- Day Headings -->
      <% days.each do |day| %>
        <td><div id="<%= day.downcase %>"><h3><%= day %></h3>
        <!-- Role Headings -->
        <% @shifts.map {|shift| shift.role unless shift.day != day}.uniq.each do |role| %>
          <section id="<%= day.downcase %>-<%= role.to_s.downcase %>">
            <strong><%= role %></strong>
            <!-- Each Shift (matching day and role) -->
            <% @shifts.select {|shift| shift.role == role && shift.day == day}.each do |shift| %>
              <section id="<%= day.downcase %>-<%= role.to_s.downcase %>-<%= shift.id %>">
                <p><u><%= link_to shift.time, shift_path(shift) %></u><br>
                Staff Needed: <%= shift.staff %><br>
                <%= link_to "(edit)", edit_shift_path(shift) if admin %> <%= " | " if admin %><%= link_to "(delete)", shift,  method: :delete, data: { confirm: 'Are you sure?' } if admin %></p>
              </section>
            <% end %>
          </section>
        <% end %>
        <div></td>
      <% end %>

  </table>

<% end %>

app/views/shifts/new.html.erb
<% if admin %>

  <h1>Shifts#new</h1>
  <p>Find me in app/views/shifts/new.html.erb</p>

  <%= render partial: "form", locals: {shift: @shift} %>
 
<% end %>

app/views/shifts/show.html.erb
<h1>Shifts#show</h1>
<p>Find me in app/views/shifts/show.html.erb</p>

<%= link_to "Add Shift", new_shift_path if admin %>

<h2><%= @shift.day %></strong></h2>
<strong><%= @shift.role.capitalize %></strong><br>
Time: <%= @shift.time %><br>
Staff Needed: <%= @shift.staff %><br>

<% if admin %>
  <%= link_to "Edit Shift", edit_shift_path(@shift) %> | 
  <%= link_to "Delete Shift", @shift,  method: :delete, data: { confirm: 'Are you sure?' } %><br><br>
<% end %>

<h3>Staff</h3>
<% @shift.users.each do |user| %>
  <%= render partial: "users/display", locals: {user: user} %>
<% end %>