config/routes.rb
Rails.application.routes.draw do

  get 'scheduled_shifts/create'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users do
    resources :requests
  end

  resources :posts do
    resources :comments
  end

  resources :tags

  resources :shifts
  
  post 'users/:id/edit' => 'users#edit'
  post 'requests/new' => 'requests#create'

  root 'users#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/form_user.rb
class FormUser < User
  attr_accessor :current_password

  validates_presence_of   :email, if: :email_required?
  validates_uniqueness_of :email, allow_blank: true, if: :email_changed?
  validates_format_of     :email, with: Devise.email_regexp, allow_blank: true, if: :email_changed?

  validates_presence_of     :password, if: :password_required?
  validates_confirmation_of :password, if: :password_required?
  validates_length_of       :password, within: Devise.password_length, allow_blank: true

  def password_required?
    return false if email.blank?
    !persisted? || !password.nil? || !password_confirmation.nil?
  end

  def email_required?
    true
  end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    identity = find_by(provider: auth.provider, uid: auth.uid)
    identity = create(uid: auth.uid, provider: auth.provider) if identity.nil?
    identity.accesstoken = auth.credentials.token
    identity.refreshtoken = auth.credentials.refresh_token
    identity.name = auth.info.name
    identity.email = auth.info.email
    identity.nickname = auth.info.nickname
    identity.image = auth.info.image
    identity.phone = auth.info.phone
    identity.urls = (auth.info.urls || "").to_json
    identity.save
    identity
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :users, through: :comments

  has_many :post_tags
  has_many :tags, through: :post_tags

  accepts_nested_attributes_for :tags, reject_if: proc {|attributes| attributes[:name].blank?}

  validates :title, presence: true
  validates :body, presence: true

  def title=(title)
    write_attribute(:title, title.upcase)
  end

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  has_many :shifts

  accepts_nested_attributes_for :shifts
end

app/models/scheduled_shift.rb
class ScheduledShift < ActiveRecord::Base
  belongs_to :shift
  belongs_to :user
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  has_many :scheduled_shifts
  has_many :users, through: :scheduled_shifts

  def add_shift(shift_id)
    scheduled_shift = scheduled_shift.find_by(shift_id: shift_id) 
    if !scheduled_shift
      scheduled_shift = self.scheduled_shifts.build(shift_id: shift_id)
    end
    scheduled_shift
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, through: :post_tags

  validates :name, uniqueness: true

  def name=(name)
    write_attribute(:name, name.downcase)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable

  validates :name, uniqueness: true
  validates :name, presence: true, on: :update
  validates :email, presence: true, on: :update
  validate :phone_ten_digits, on: :update, unless: :phone_blank

  has_one :identity
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :scheduled_shifts
  has_many :shifts, through: :scheduled_shifts
  has_one :request
  accepts_nested_attributes_for :shifts

  has_many :posts, through: :comments
  has_many :comments

  def self.best_users
    self.all.where(rating: 'high')
  end

  def phone_blank
    self.phone.to_s == ""
  end

  def phone_ten_digits
    if self.phone.gsub(/[^\d]/, '').length != 10
      errors.add(:phone, "number must include exactly 10 digits.")
    end
  end

  def slug
    self.name.downcase.gsub(" ","-")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json, :js

  def index
    @posts = Post.all
    @users = User.all
    respond_with @posts
  end

  def new
    @post = Post.new
    @post.tags.build
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_with @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
    respond_with @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, tag_ids: [], tags_attributes:[:name])
  end
  

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :find_shift, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js, :json

  def index
    @shifts = Shift.all
    respond_with @shifts
  end

  def new
    @shift = Shift.new
    respond_with @shift
  end

  def create
    @shift = Shift.create(shift_params)
    respond_with @shift
  end

  def show
    respond_with @shift
  end

  def edit
  end

  def update
    if @shift.update_attributes(shift_params)
      redirect_to @shift
    else
      render 'edit'
    end
  end

  def destroy
    @shift.destroy
    redirect_to shifts_path
  end

  private

  def shift_params
    params.require(:shift).permit(:role, :staff, :time, :day)
  end

  def find_shift
    @shift = Shift.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :find_shifts, only: [:index, :show, :edit]
  respond_to :html, :js, :json
  
  def index
    @users = User.all
    @best_users = User.best_users
    respond_with @users
  end

  def show
    respond_with @user
  end

  def edit
    @request = Request.new
  end

  def update
    if @user.role != params[:user][:role]
      @user.shifts.clear
    end
    if @user.update_attributes(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :phone, :role, :rating, :avatar, :gender, shift_ids: [])
  end

  def find_user
    @user = User.find(params[:id])
  end

  def find_shifts
    @shifts = Shift.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :phone, :role, :rating)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

<h2>
  <%= @tag.name %>
  <%= link_to "(delete)", @tag, method: :delete, data: { confirm: 'Are you sure?' } if admin %>
</h2> 

<% @tag.posts.each do |post| %>
  <p><strong><%= post.title %></strong>
  <br><em><%= post.updated_at.strftime("Posted on %B %d, %Y") %></em>
  <p><%= post.body %></p>
  Tags:
  <% post.tags.each do |tag| %>
    <%= link_to "#{tag.name}", tag_path(tag) %>
  <% end %>

  <% if admin %>
    <p>
      <%= link_to "Edit Post", edit_post_path(post) %> |
      <%= link_to "Delete Post", post,  method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
<% end %>

app/views/users/_admin.html.erb
<% if admin %>  
    <section id="admin-panel-<%= user.slug %>">
        <br><strong><%= link_to "Admin Panel", "#", class: :admin_link %></strong><br>

        <%= form_for user, html: {class: :admin_panel} do |f| %>

            <%= f.radio_button :gender, 'm' %> 
            <%= label :gender, 'Man' %>
            <%= f.radio_button :gender, 'w' %>
            <%= label :gender, 'Woman' %><br>

            <%= f.radio_button :role, 'Manager' %> 
            <%= label :role, 'Manager' %>
            <%= f.radio_button :role, 'Counter' %>
            <%= label :role, 'Counter' %>
            <%= f.radio_button :role, 'Busser' %>
            <%= label :role, 'Busser' %><br>

            <%= f.radio_button :rating, 'high' %> 
            <%= label :rating, 'High' %>
            <%= f.radio_button :rating, 'medium' %>
            <%= label :rating, 'Medium' %>
            <%= f.radio_button :rating, 'low' %>
            <%= label :rating, 'Low' %>

            <br><%= f.submit "Save changes" %>

        <% end %><br>
    </section>
<% end %>

app/views/users/_admin_shift.html.erb
<% if admin %>  
  <strong>Shift Panel</strong>

  <% if !@shifts.map {|shift| shift.role}.include?(user.role) %>
    <br><em>No <%= user.role.downcase %> shifts exist.</em><br>
  <% else %>
    <%= form_for(user) do |f| %>
      <% ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].each do |day| %>
        <% if @shifts.map {|shift| shift.day unless shift.day != day || shift.role != user.role}.include?(day) %>
          <u><%= day %></u><br>
          <%= collection_check_boxes(:user, :shift_ids, @shifts.where(role: user.role, day: day), :id, :time) %><br>
        <% end %>
      <% end %>
      <%= f.submit "Save shifts" %>
    <% end %>    
  <% end %>
<% end %><br> 

app/views/users/_display.html.erb
<section id="display-<%= user.slug %>">

  <% if user.avatar_file_name != nil %>
    <%= link_to image_tag(user.avatar.url, size: "200x200"), user_path(user) %><br>
  <% elsif user.identity %>
    <%= link_to image_tag(user.identity.image, size: "200x200"), user_path(user) %><br>
  <% end %>

  <strong><%= link_to user.name.to_s + "#{user.role != '' ? ', ' + user.role.to_s.capitalize : nil}", user_path(user.id) %></strong> <%= link_to "(edit)", edit_user_path(user) if user.email == current_user.email || admin %>

  <% if admin || user.email == current_user.email %>
    | <%= link_to "(delete)", user,  method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>

  <br>

  <em><%= user.created_at.strftime("Joined on %B %d, %Y") %></em><br>

  <% if user.phone == nil || user.phone == "" %>
    <% if user.email == current_user.email || admin %>
      <%= link_to "[ADD PHONE]", edit_user_path(user) %>
    <% else %>
      <em><%= "Phone pending" %></em>
    <% end %>
  <% else %>
    <%= number_to_phone(user.phone.gsub(/\D/,"").to_i, area_code: true) %>
  <% end %>

  | <%= user.email %><br><br>

  <strong>Schedule</strong>
  <% if user.shifts.empty? %>
    <br><em>Not scheduled</em>
  <% else %>
    <% user.shifts.each do |shift| %>
      <br><%= link_to "#{shift.day}: #{shift.time}", shift %>
    <% end %>
  <% end %><br>

  <%= render partial: "/requests/availability", locals: {user: user, request: user.request} %>

</section>

app/views/users/_shift.html.erb
<% if admin %>
  <section id="shift-panel-<%= user.slug %>">
    <strong><%= link_to "Shift Panel", "#", class: :shift_link %></strong>

    <% if user.role.blank? %>
      <br><em>Has not been assigned a role.</em><br>
    
    <% elsif !@shifts.map {|shift| shift.role}.include?(user.role) %>
      <br><em>No <%= user.role.downcase %> shifts exist.</em><br>
    
    <% else %>
      <%= form_for user, html: {class: :shift_panel} do |f| %>

        <% days.each do |day| %>
          <% if @shifts.map {|shift| shift.day unless shift.day != day || shift.role != user.role}.include?(day) %>
            <u><%= day %></u><br>

            <%= hidden_field_tag "user[shift_ids][]", nil %>

            <% @shifts.where(role: user.role, day: day).each do |shift| %>
              <%= check_box_tag "user[shift_ids][]", shift.id, user.shift_ids.include?(shift.id) %>
              <%= shift.time %><br>
            <% end %>

          <% end %>
        <% end %>
        
        <%= f.submit "Save shifts" %>

      <% end %>    
    <% end %>

  </section>
<% end %><br> 

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<% if @user.avatar_file_name != nil %>
  <%= image_tag(@user.avatar.url, size: "200x200") %><br>
<% elsif @user.identity %>
  <%= image_tag(@user.identity.image, size: "200x200") %><br>
<% end %>

<%= form_for @user do |f| %>
  
  <div>
    Photo: <%= f.file_field :avatar %>
  </div> 
  
  <div>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>
  </div>

  <div> 
    <%= f.label :phone, "Phone:" %>
    <%= f.text_field :phone %><br>
  </div>

  <div> 
    <%= f.label :email, "Email:" %>
    <%= f.text_field :email %><br><br>
  </div>

  <%= f.submit "Update Profile" %> 

<% end %><br>

<% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<% if !@best_users.empty? && admin %>
  <strong>Top Rated Employees</strong>
  <% @best_users.each do |user| %>
    <br>- <%= link_to "#{user.name}, #{user.role}", user_path(user) %>
  <% end %><br><br>
<% end %>

<table id="user_index">
  <% @users.sort_by {|k,v| k[:role]}.reverse.in_groups_of(4, false).each do |user_array| %>
    <tr>
      <% user_array.each do |user| %>
            
        <td id="<%= user.slug %>"><div><%= render partial: "display", locals: {user: user} %>

        <%= render partial: "admin", locals: {user: user} %>

        <%= render partial: "shift", locals: {user: user} %></div></td>

      <% end %>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

<%= render partial: "display", locals: {user: @user} %><br>

app/views/welcome/edit.html.erb
<h1>Welcome#edit</h1>
<p>Find me in app/views/welcome/edit.html.erb</p>

<% if @user.identity %>
  <%= image_tag(@user.identity.image) %><br>
<% end %>

<%= form_for welcome_path(@user) do |f| %>

  <div>
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name %>
  </div>

  <div> 
    <%= f.label :phone, "Phone:" %>
    <%= f.text_field :phone %><br>
  </div>

  <% if current_user.email == "zach.newburgh@gmail.com" %>
    <div>
      <%= f.radio_button :role, 'manager' %> 
      <%= label :role, 'Manager' %>
      <%= f.radio_button :role, 'counter' %>
      <%= label :role, 'Counter' %>
      <%= f.radio_button :role, 'busser' %>
      <%= label :role, 'Busser' %>
    </div>

    <div>
      <%= f.radio_button :rating, 'high' %> 
      <%= label :rating, 'High' %>
      <%= f.radio_button :rating, 'medium' %>
      <%= label :rating, 'Medium' %>
      <%= f.radio_button :rating, 'low' %>
      <%= label :rating, 'Low' %>
    </div>
  <% end %>

  <div>
  <%= f.submit "Update" %>
  </div>
<% end %>
  

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<% @users.sort_by {|k,v| k[:email]}.each do |user| %>
  <div>
    <% if user.identity %>
      <%= link_to image_tag(user.identity.image), welcome_path(user) %><br>
    <% end %>

    <strong><%= link_to "#{user.name ||= user.identity.name}\n", welcome_path(user.id) %></strong><br>
    <%= user.email %><br>
    <em><%= user.created_at.strftime("Joined on %B %d, %Y") %></em>

    <% if current_user.email == "zach.newburgh@gmail.com" %>
      <%= form_for :user, method: :patch do |f| %>

        <%= f.radio_button :role, 'manager' %> 
        <%= label :role, 'Manager' %>
        <%= f.radio_button :role, 'counter' %>
        <%= label :role, 'Counter' %>
        <%= f.radio_button :role, 'busser' %>
        <%= label :role, 'Busser' %><br>

        <%= f.radio_button :rating, 'high' %> 
        <%= label :rating, 'High' %>
        <%= f.radio_button :rating, 'medium' %>
        <%= label :rating, 'Medium' %>
        <%= f.radio_button :rating, 'low' %>
        <%= label :rating, 'Low' %><br>
        <%= f.submit "Update" %>
      <% end %><br>
  <% end %>

  </div>
<% end %>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/show.html.erb</p>

<% flash[:success] ? "#{flash[:success]} \n" : nil  %>

<% if @user.identity %>
  <%= image_tag(@user.identity.image) %><br>
<% end %>
<strong><%= @user.name ||= @user.identity.name %></strong><br>
<%= @user.phone %>
<%= @user.email %><br>
<em><%= @user.created_at.strftime("Joined on %B %d, %Y") %></em><br>
<%= link_to "Edit", edit_welcome_path(@user) if @user == current_user || current_user.email == "zach.newburgh@gmail.com" %><br>