config/routes.rb
Rails.application.routes.draw do

  get 'scheduled_shifts/create'

  devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users do
    resources :requests
  end

  resources :posts do
    resources :comments
  end

  resources :tags

  resources :shifts
  
  post 'users/:id/edit' => 'users#edit'
  post 'requests/new' => 'requests#create'

  root 'users#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :users, through: :comments

  has_many :post_tags
  has_many :tags, through: :post_tags

  accepts_nested_attributes_for :tags, reject_if: proc {|attributes| attributes[:name].blank?}

  validates :title, presence: true
  validates :body, presence: true

  def title=(title)
    write_attribute(:title, title.upcase)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json, :js

  def index
    @posts = Post.all
    @users = User.all
    respond_with @posts
  end

  def new
    @post = Post.new
    @post.tags.build
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_with @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build
    respond_with @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, tag_ids: [], tags_attributes:[:name])
  end
  

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br><br>

  <%= f.label :body %><br>
  <%= f.text_area :body, size: "50x5" %><br><br>

  <%= f.fields_for(:tags) do |tag_form| %>
    <%= tag_form.label :name, "Tag" %><br>
    <%= tag_form.text_field :name %>
  <% end %>

  <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br><br>

  <%= f.submit %>
<% end %><br>

<% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %>
<% end %>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<%= render partial: "form", locals: {post: @post} %>

app/views/posts/index.html.erb
  <h1>Posts#index</h1>
  <p>Find me in app/views/posts/index.html.erb</p>

  <% if admin %>
    <%= link_to "Add Note", new_post_path, id: "new_link" %>
  <% end %>

<div id="posts">
  <% @posts.each do |post| %>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <em><%= post.updated_at.strftime("Posted on %B %d, %Y") %></em>
    <br>Tags: <% post.tags.each do |tag| %>
      <%= link_to "#{tag.name}", tag_path(tag) %> 
    <% end %>


    <% if admin %>
      <p>
        <u>Not yet commented:</u>
          <% @users.map {|user| user.name}.reject{|name| name if post.comments.map {|comment| comment.user.name}.uniq.include?(name)}.each do |name| %>
            <li><%= name %></li>
          <% end %> 
      </p>

      <p>
        <%= link_to "Edit Post", edit_post_path(post) %> |
        <%= link_to "Delete Post", post,  method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>

    <strong><%= link_to "Comments", post_comments_path(post), id: "load_comments" %></strong>
    <div class="comments">
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= render partial: "form", locals: {post: @post} %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<h2><%= @post.title %> <%= link_to "(edit)", edit_post_path(@post) if admin %><%= " | " if admin %><%= link_to "(delete)", @post, method: :delete, data: { confirm: 'Are you sure?' } %> </h2>
<em><%= @post.updated_at.strftime("Posted on %B %d, %Y") %></em>
<p><%= @post.body %></p>
Tags:
<% @post.tags.each do |tag| %>
  <%= link_to "#{tag.name}", tag_path(tag) %>
<% end %><br><br>

<h3>Comments</h3>

<div id="comments">
  <% @post.comments.each do |comment| %>
    <p>
      <%= comment.body %>
    </p>
  <% end %>
</div>

<%= render partial: "comments/form", locals: {post: @post, comment: @comment} %>